# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version=1.0.0
mod_id=echo_seed
maven_group=com.euphony.echoseed
archives_name=echo-seed
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=26.1.2

# Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
neoforge_version=26.1.2.95
yacl_version_fabric=3.9.6+26.1-fabric
yacl_version_neoforge=3.9.6+26.1-neoforge
modmenu_version=18.0.0
