modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = "https://github.com/pynickle/Echo-Seed/issues"
license = "MIT"

[[mods]]
modId = "echo_seed"
version = "${version}"
displayName = "Echo Seed / 回响种子"
authors = "ENC_Euphony"
logoFile = "icon.png"
logoBlur = false
description = '''
A Presence-grown plant whose Echo Fruit marks a place and later returns you there.
'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.echo_seed]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.echo_seed]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.echo_seed]]
modId = "yet_another_config_lib_v3"
type = "optional"
versionRange = "[3.9,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "echo_seed.mixins.json"
